ElementsProperties = [
    {name:"H", fullname:"Hydrogen", number:1, category:"Other Nonmetal" },
    {name:"He", fullname:"Helium", number:2, category:"Noble Gas" },
    {name:"Li", fullname:"Lithium", number:3, category:"Alkali Metal" },
    {name:"Be", fullname:"Beryllium", number:4, category:"Alkalin Earth Metal" },
    {name:"Be", fullname:"Beryllium", number:4, category:"Alkalin Earth Metal" },
    {name:"B", fullname:"Boron", number:5, category:"" },
    {name:"C", fullname:"Carbon", number:6, category:"" },
    {name:"N", fullname:"Nitrogen", number:7, category:"" },
    {name:"O", fullname:"Oxygen", number:8, category:"" },
    {name:"F", fullname:"Fluorine", number:9, category:"" },
    {name:"Ne", fullname:"Neon", number:10, category:"" },
    {name:"Na", fullname:"Sodium", number:11, category:"" },
    {name:"Al", fullname:"Aluminium", number:13, category:"" },
    {name:"Si", fullname:"Silicon", number:14, category:"" },
    {name:"P", fullname:"Phosphorus", number:15, category:"" },
    {name:"S", fullname:"Sulfur", number:16, category:"" },
    {name:"Cl", fullname:"Chlorine", number:17, category:"" },
    {name:"Ar", fullname:"Argon", number:18, category:"" },
];
